version: "3.8"
services:
  dev-db:
    image: postgres:13
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DATABASE: nest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mynewpassword